### ISSUE TITLE
FR Translation contribution

### ISSUE THREAD

**Issue by pilax** [brainfoolong/IntoTheBreachTranslations#2]
Hello,

I saw your message on the ITB forum about a tool for translating the game into several languages ​​and I think it's a good initiative.

I would like to participate, if possible, in the translation of the game into French.

I also saw that Blue_Tree was working on it too (https://www.subsetgames.com/forum/viewtopic.php?f=26&t=32802) for the FR version and that Metalwar was doing the Spanish version (https://www.subsetgames.com/forum/viewtopic.php?f=26&t=32829)

Did you come into contact with them to merge your work and bring everything together under your project?

I created my account on the SubsetGames forum, wishing to suggest the merger to the various people working on it, but I never received the activation email, I contacted an Admin to solve this problem. I am currently waiting ...

So for now, I can not write message on the forum, that's why I make you this suggestion right here.

It would be stupid for me to start translating the game related to your project, while for its part, another person is translating it too, as much to put efforts in commum;)

I hope I can help and move the project forward.
Regards,

Pilax

**Comment by brainfoolong** [comment]
I have saw those topics but not contacted that people right now. At first i would like to bring this to a good level for others to start with.

Currently things changing and many translation keys are missing because it's a manual progress to find that last 30% in all the game files.

But i will do a first contact to this projects soon.

**Comment by pilax** [comment]
Thank you for your quick reply.

Ok I understand that you expect to have a project well advanced before offering it to other people, but maybe they can help you for the remaining 30%.
It seems to me that the latest files are pictures with text that must be redone in part, as was the case for FTL.

Anyway, I remain available if you want a contribution for FR translation.
Good luck for the rest of the project.

Pilax

**Comment by brainfoolong** [comment]
Thanks. The work of finding the correct things in the files is maybe just a thing for me only, as it requires some knowledge how this project is working internally.

I want to provide tools for translators to focus on just translatiing things, not waisting their time with digging into game files.

For that reason it is the most easy thing here to contribute a translation. Just use the free tool "PoEdit", modify the .po file and everything else will be created from tools automatically.

**Comment by pilax** [comment]
Ok I see !
Indeed such a tool would be great and greatly simplify the work of translators.
I will follow the progress of your project and I hope that it will be used later by the different people wishing to translate the game into their language.

For my part, I will start working locally on translation of the "template.po" file into "french.po" and send it to you when everything is ready on your side.

By then, good luck for data mining :)

Pilax

**Comment by brainfoolong** [comment]
Not required. I created a `fr.po` that you can start of, right a few secs ago.

**Comment by pilax** [comment]
Yeah I saw that after my message.
you're faster than Speedy Gonzales !

Thanks a lot brainfoolong 👍

**Comment by brainfoolong** [comment]
There is a new way of how to translate this project. Please do the following.
1. Commit all your work, even if it's unfinished and create pull requests.
2. When pull requests are done, i will merge them and convert the `.po` files to the new format
3. I come back to you when all is done with a guide to how to translate from now

**Comment by pilax** [comment]
Hello,
OK no problem. Done for me.

I saw that you were adding new tools on the project and I was planning to send you a message about it, but you took the lead.

I still have a question, I taged some translations in "to review" in Poedit, can I find it with the new tool to modify my translation?

Looking forward to your next message to resume the translation.

**Comment by brainfoolong** [comment]
The tools are ready later this day. `To review` is possible in the new tool also but the flags are not exported to the new file format. You should remember this lines and mark it again later in the new tool.

**Comment by pilax** [comment]
Ok I waiting for the new tools :)

No problem, I keep a backup of my work, I could compare the lines taged in Poedit with that of the new tool to find them easily.

Thank you for the work you do!

**Comment by brainfoolong** [comment]
Ok. Translation from now is different than before. Everything what is required is here -> https://github.com/brainfoolong/IntoTheBreachTranslations/tree/master/dev/editor

**Comment by pilax** [comment]
Ok thanks you.
I'm looking at the new method and i get to work

**Comment by pilax** [comment]
I have a problem with using the new tool.
I have an error message when I execute `node server.js` command from `/dev` directory : 

```
module.js:545
    throw err;
    ^

Error: Cannot find module 'D:\Tools\GitHub\ForkIntoTheBreachTranslations\dev\server.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
```

If I execute `node server.js` command from `/dev/editor/` directory : 

```
module.js:545
    throw err;
    ^

Error: Cannot find module 'qs'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Tools\GitHub\ForkIntoTheBreachTranslations\dev\editor\server.js:6:21)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
```

below the contents of the config.js file : 
```
'gamedir': 'D:/Steam/steamapps/common/Into the Breach'
'gamesrc': 'D:/Tools/BK Files/backup patch'
'langInGameDir': 'fr'
'googleTranslateKey': null
'editorPort': 6161
'editorLanguage': 'fr'
```

If you can help me please :) 
PS : Of course I'm working on local files

**Comment by brainfoolong** [comment]
Re-Clone/Download everything. Than run `npm install` on main directory (where `package.json` is). Than start the server. I will update editor readme.

**Comment by pilax** [comment]
ok I try, ty for your quick answer

**Comment by pilax** [comment]
Same error again.

What do you mean `Run node server.js in this directory` ?
- should we copy the server.js file into /dev?
- because if I execute the command as it does not work, I have the same error message as my previous message

Maybe I'm doing something wrong, or have I misunderstood?

EDIT : ok, I found my error. We need to get in editor directory and execute the commande.
Don't stay on /dev.
May modify Readme to clarify more ?

**Comment by brainfoolong** [comment]
Hm. Thats weird. I have done the steps right now like this
* Cloned to disk
* Goto cloned directory, run `npm install`
* Edited the `dev/config.js` to my needs
* Goto `dev/editor` and run `node server.js`
* Message `Server running at http://localhost:6161/ - Open it up in your browser` shown and server is running

Maybe you are not on the current master with this repository? Edit: Scratch that, I've tested it from your fork also, work fine here.

Maybe show the output from `node -v`

**Comment by brainfoolong** [comment]
Allright. I update the readme better :)

**Comment by pilax** [comment]
Yeah all steps are good exept one In the Readme.

This line is good here : 
- Goto dev/editor and run node server.js

But in the Readme, you got this : 
- Copy `dev/config.tpl.js` to `dev/config.js` and modify it to your needs
- Run `node server.js` in this directory and open up http://localhost:6161 in your browser - Chrome works best here

Here, we understand we need to execute `node server.js` since /dev directory and note since /dev/editor.
So it is confusing :/

**Comment by brainfoolong** [comment]
Yes, updated. Thx for testing.

**Comment by pilax** [comment]
Yes saw this, more clear :)
Ty !

**Comment by mengpo1** [comment]
Hi both of you, 

I was working on the pilax translation (mainly correcting typos) and I did not see that the tool editor changed yesterday and I did not pull the work. How do I convert the po file into a json one please ? 

Thanks for both of you for your work, you're doing a great job !

@pilax : chapeau bas pour ton boulot ;) Il faudra que l'on discute de deux-trois notions traduites afin que je comprenne le pourquoi du comment de la traduction :)
(Amazing work ! We'll need to discuss some of the notions translated so I would understand why you translate them this way) 

Thanks again :)

**Comment by brainfoolong** [comment]
Well, that's bad now. I only knew from that, that forked that repository.

Unfortunetely, you have to manually merge that into the new translation file, it's best to talk with @pilax directly for that issue.

Sorry for the inconvenience, but it was required to update the tools.

**Comment by mengpo1** [comment]
Oh don't worry, I always take my time for all kind of things, I wasn't quick enough that's my fault XD
I'll talk to @pilax for the modifications ;)

Thanks :D

**Comment by pilax** [comment]
Hi there !

Thanks you mengpo1, it's a pleasure !

Good news @mengpo1, your help will not be too much I think ;)
Let's take contact together and see how we can merge your work with mine :)

Indeed it would be nice if we discuss on certain translation term so that the overall translation is homogeneous.

(Salut @mengpo1,

Merci à toi, ca fait plaisir !
Comment souhaites tu rentrer en contact ? Via Teamspeak, Discord, autre ?
Je suis disponible une bonne partie de l'après midi si besoin ;) )

**Comment by mengpo1** [comment]
Hi Pilax !

Thanks ! I'm installing discord right now (never used it XD), Here is my tag #2234.

I'm kidda busy till monday (maybe I'll have time to work on the translation sunday. Don't be surprised if I'm a bit slow to answer).  

See ya on discord and here too ;)

**Comment by pilax** [comment]
Added! 
Welcome into the breach of this project ^^

**Comment by brainfoolong** [comment]
So, finally i have created to tools to pack/unpack all images and font files from the game file `resource.dat`. Now it should be possible to experiment with font/image modifying.

**Comment by pilax** [comment]
Oh yes ! what a good news and good things.
But how does it works ?

I used FTL [FTL Unpacker](https://www.subsetgames.com/forum/viewtopic.php?f=12&t=2788&hilit=/)  for pack/unpack `resource.dat` with the modified font.

As for the fonts, I was able to use the one used in part for FTL and modified by blue_tree for into the breach.
But some characters still appear in "?".
I will have to look into this problem once the translation is well advanced.

As for images, it will ask for work too, but I hope not infeasible :)
On the other hand, I do not know where to find them, compared to the fonts.

**Comment by brainfoolong** [comment]
Basically it's the same thing, but i have written it for nodejs and integrated it into this toolchain. This means, you can still use any FTL Unpacker and modify the files to your needs. If you have, for example, some modified fonts or images that work for your language, you can commit it to the github directory `dev/dat-files-modified/{yourlanguage}/{yourresourcedatafile}` -> Than this files will automatically be integrated in the next `language.zip` in this repository, by automatically unpacking the original `resource.dat`, merging your modified files into it, repack the `resource.dat`, and include it in the `.zip` file.

Some black magic 👍

**Comment by brainfoolong** [comment]
Or when you want to use this tool to unpack your `resource.dat`, just run `node dev/resource-dat-unpack.js`. If you want to pack it back to `resource.dat` than run `node dev/resource-dat-pack.js` -> This will generate the file in `dev/dat-generated`

This really extract all resource files, images and fonts and other stuff int `dev/dat-files-extracted`

**Comment by pilax** [comment]
Oh Wow ! You are a monster of coding ^^

Two ways to do it, it's great!
Thank you for these two additional tools :) Very good jobs !

I have a question about the first method, should we put the different files as is in the directory, or is there a tree to respect?
For exemple : `dev/dat-files-modified/fr/Fonts/` to put in all font or `dev/dat-files-modified/fr/Images/`  to put in all images etc..

thanks again for your great tools and job you doing 👍

**Comment by brainfoolong** [comment]
Thx :) It must be the same tree as the original `resource.dat`.
Btw. i've added some readme to the dev folder. https://github.com/brainfoolong/IntoTheBreachTranslations/tree/master/dev

**Comment by pilax** [comment]
ok for the tree, it seemed logical, but given that you automate a lot of things, I prefer to ask the question, (and do not make a dumpling as for the template.json: p)

Yep, I saw the readme, I am doing the tests locally, precisely, there is a part that I do not understand well:

> To re-pack the resource.dat run `node resource-dat-unpack.js` - `dat-files-extracted/*` and `dat-files-modified/{language}/*` into `dat-generated/resource.dat`

What do you mean ? I don't understand command order or simply just what to do :/
Could you be more clear in the commands to type?

Sorry, and ty by advance

**Comment by brainfoolong** [comment]
Sry for that unclear, you have just to run `node resource-dat-pack.js`, the other text is the description what it does. PS: there is a typo in the readme, see the command in this comment.

**Comment by pilax** [comment]
ah ok, no problem.
I saw readme modify, it's more clear ;) Thanks you.
But as a problem never comes alone: /

In advance I apologize if I ask a lot of questions, which could be obvious, I work as a IT technician, however I am not dev at all, I understand nothing in the code, or very little :( to my regret. .
Anyway next..

I try to unpack with this `node resource-dat-unpack.js`
got this : 
```
fs.js:667
  return binding.open(pathModule.toNamespacedPath(path),
                 ^

Error: ENOENT: no such file or directory, open 'D:\Tools\GitHub\ForkIntoTheBreachTranslations\dev\ToolsBK FilesInto the Breach\resources\resource.dat'
    at Object.fs.openSync (fs.js:667:18)
    at Object.fs.readFileSync (fs.js:572:33)
    at Module.module.exports (D:\Tools\GitHub\ForkIntoTheBreachTranslations\dev\resource-dat-unpack.js:9:26)
    at Object.<anonymous> (D:\Tools\GitHub\ForkIntoTheBreachTranslations\dev\resource-dat-unpack.js:71:8)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)

```

Why searching here : `D:\Tools\GitHub\ForkIntoTheBreachTranslations\dev\Tools` 
Doesn't the path in my config.js and don't have this directory, must be create before ?
or I missed something somewhere?

I am your modest beta tester :)

**Comment by brainfoolong** [comment]
In your `config.js` your `gamesrc` folder must point to a copy of your game folder. 

A second thing could be a "backslash" in this path.

On windows, the backslashes `\` are a problem. Replace it with `/`. In javascript the `\` means you `escape` the next character. Which effectively "hides" the backslash. With a normal slash all should work fine.
Also don't forget your drive letter at beginning, for example `c:/`

An, ask what you have to ask, its cool to have such an effective tester.

**Comment by pilax** [comment]
But what an idiot!
I had not made this mistake the previous times (has you can see on previous post), and I thought to replace the `\` with `/`, but not this time, all my excuses, inattention on my part!

But by the way, may be good to specify somewhere in the readme, if I got me, then other will face the same problem i think;)

**Comment by brainfoolong** [comment]
Already done 👍 Give me a feedback of those packer worked fine for you.

**Comment by pilax** [comment]
I just made a change to the readme.
concerning the other tools, I'll keep you informed as and when my tests;)

**Comment by pilax** [comment]
Following my tests.
Here is what I did:
- I run `node resource-dat-unpack.js` : no problem, directory and extracted files correctly.
- I created in `dev/dat-files-modified/` the directories: `fr/fonts` and `fr/img`
- I copied fonts modified by blue_tree in the directory `dev/dat-files-modified/fr/fonts` to make a test (even if it is not complete for the moment)
- I run `node resource-dat-pack.js` : KO. here is the error message:

`
Error: ENOENT: no such file or directory, copyfile 'D:\Tools\GitHub\ForkIntoTheBreachTranslations\dev\dat-files-modified\fr\fonts\c&c.ttf' -> 'D:\Tools\GitHub\ForkIntoTheBreachTranslations\dev\dat-files-extracted\fr\fonts\c&c.ttf'`

It seems that the script looks for the same tree, namely here the directory `/fr` in `/dev/dat-files-extracted/`.

I suppose, if create `/fr` into `/dev/dat-files-extracted/` it will work, but I do not think your script is intended to work like that :)

In passing a stupid  question on the operation of the script.
At the time of the repack the script retrieves the files located in `/dev/dat-files-extracted/` and `/dev/dat-files-modified/{language}/`, I suppose that by generating the `resources.dat`, if files are `/dev/dat-files-modified/{language}/`, it will not take the corresponding file in `/dev/dat-files-extracted/`, isn't it?

**Comment by brainfoolong** [comment]
You are right, if no modified file exist, it takes the original.

The tool had a bug in it, i fixed it already.

**Comment by pilax** [comment]
Ok for that, thanks, more clear for me ;)

So, i'll update my fork and try again.

When you modify a script, did we run a command to refresh all (like npm install) or not ?

**Comment by pilax** [comment]
Ok all look fine right now. Thank you for your responsiveness !
`Ressources.dat` correctly generated.

I run `node update-translation-packs.js` : all look fine too.
Launch my game : all look fine :) Translate and font in place :D 

Great jobs !

Last question : when I want to generate `resource.dat` again, should i delete the previous one, or will it overwrite it?

**Comment by brainfoolong** [comment]
It's always good to run `npm install` after tools has been updated, because it can contain new required libraries. But that's all what you have to do.

And you don't have to delete the generated `resource.dat` file, it will be overwritten.

**Comment by pilax** [comment]
Ok, I'll do it for next time, although I did it this time in doubt :p 
Ok for overwritting.

At work now for me ! Everything seems ok.
Thank you for everything !

**Comment by mengpo1** [comment]
Hi Brainfoolong,

I've been working on the translation using your tool on Pilax's fork (almost for a month now) but today I've had some difficulties to update our work (when I try to upload it to github). Did you update your tool ou something on your github ? Should Pilax update his fork ?

Thanks your all yor work (I never thanked you before for that ;))

**Comment by brainfoolong** [comment]
Hi!
I cannot say whats going wrong on your side. Maybe you have conflicts, maybe you have used some old translation files. Maybe pilax can help you.

**Comment by mengpo1** [comment]
So you didn't do anything to your tool ? :)

Okay I'll ask Pilax tonight ;) 

Thanks !

**Comment by brainfoolong** [comment]
I cannot exactly say with what you are working with. Which code-base do you have used or whatever. Too many variables here to make a guess. I have worked on the tools every day in the last month. It's like that your or pilax fork is outdated.

In any way, pilax can help you the best when you worked on his fork.

**Comment by mengpo1** [comment]
Sorry about that, I didn't mean to upset you, I didn't realize that. I've been in the translations for days now and tend to forget that anything is not as simple as translating things (such as the tools you provided for example). 

I think you're right by saying that our tools are outdated. Anyway, I'll ask Pilax to give a look.

Sorry and Thanks !

**Comment by pilax** [comment]
Hi there,

As soon as a change was made on the master, I updated the Fork.
It's been almost a month since there was no modification on the Master, so I did not need to update the Fork.
I have been using online translation tools since availability, and I have not had a problem so far. (Except thinking of reloading the page once the "upload to github" function is used, otherwise an error message appears).

So I don't know what's appening. Let's see together what appening ;)

**Comment by pilax** [comment]
Ok, after a little research, I found where the problem comes from, but I do not know how to solve it, and it seems that it has occurred since Difonzo's pull request.
Can you enlighten me Brainfoolong?

I expose the problem:
Following the exchange above between you and mengpo, I wanted to update the Fork, via the merge command to then cleanly upload the file "fr.json" (that mengpo to save locally and sent me).

But when I want to update my fork (command line or Github Desktop) I get an error message:
```
error: Merging is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
```
It seems that the problem comes from the file "readme.md" (there is an error icon next to the file in Github Desktop, telling me the file that is problematic) but I do not know how to solve it without breaking everything I would like to learn how to do it properly.

An idea ?

Thank you in advance !

Edit : I think the concern comes from the tool that automatically updates the translation progress badge.

I do not know how to explain this, but on our side we advance on the translation without making a pull request to the master.
On the other side, you make your translation, and yet another is Difonzo for the Italian part.

The tool automatically updates the readme as soon as we advance on the translation on each fork, but as soon as one of us makes a pull request to the master, then the readme differs on each one and prevents to make a merge of master to a fork.

I do not know if my explanation is clear, and if the problem comes from there, but in any case, it is on the readme file that the problem arises when I want merge of the master towards my fork.

**Comment by pilax** [comment]
Ok problem solved!
In advance, I apologize for the block that will follow, but I think I detected a bug and I also have some questions in passing ..

Let's proceed in order, let's start with the problem we encountered today and how I solved it temporarily.

Mengpo and I both work on my Fork, directly using the online tools for translation. Mengpo has contributor access on my Fork and can thus advance on the translation of his side.

On my side I take care of executing the scripts locally to update the package fr.zip and the resource.dat when necessary, and the upload on my Fork.

Until today, we have always done so without problem.

But today, following Difonzo's pull request from his Fork to your Master, we were unable to update the translation file "fr.json" via the online tool by clicking on "upload to github".
Unfortunately I do not have the said message, having not worked on the tool today, only Mengpo raised the problem.

Following this there was the message exchange above.

I wanted to merge the master to my Fork, but could not, because of the error message indicated in previous messages.

Going through GitHub Desktop, I ignored the merge of the file "Readme.md" to update the clone of my fork locally from your Master.
I replaced the file "fr.json" that Mengpo sent me, always on the clone of my fork in local.
I ran the node script "update-translation-packs.js" to update the package.
Then I push the local clone files to the Fork on Github.
After that we could use the online translation tool and upload to Github without any problem.

At this point the primary problem has been solved, but on the other hand it has been raised.

The README.MD that was automatically generated by the scripts had some errors in the header (duplicates and bits of code that appeared in text format), I had to manually edit it locally to clean what does not not going for the push on my Fork.
Certainly due to the fact that he did not want this update since the master previously.

So it would have two problem with this file, certainly related:
When a Fork makes a Pull request to the Master, and another person wants to Merge the Master to his Fork afterwards:
- There is an error for merge the readme file
- Forks can no longer use the online tool until the merge from the master has been done (which refers to the previous problem)

The solution is to ignore the merge of the Readme file, but on the other hand it creates a problem in the header of the file during the execution of the script as I described it above.

Here is the problem detected today and my return.

On the other hand we have another error message with the online tool that has been present since it was made available, so independent of today's problem
Upload error: languages ​​/ fr.json does not match e9c36d6571dabf87791ef3e68ea9e5802f470e13

That this product when we translate some lines, that we "upload to github", we continue the translation, then "upload to github", that's when the error message appears, but it seems that this partially updates the file on the fork.
To avoid the error message, you need to "reload page" between each "upload to github".
I do not know if it's a bug or normal behavior :)


Last things concerning the resource.dat:
- Why is it ignored when pushing the local clone to the fork?
- Is it normal that he is not in fr.zip?
For currently, it is not available to players who wants the translation of the game (font and image included).
- When executing the script "run node update-translation-packs.js" would it be possible that the resource.dat is also copied in the directory of the game in order to be able to test directly, being already the case for the files of translations.
Thank you in advance :)

I'm finally done with this novel, I'm sorry, I hope you have taken the blow to the end! :)
Thanks to you and I remain at your disposal if you need additional information, or to make tests;)

Pilax.

**Comment by brainfoolong** [comment]
Thanks for this detailed information. Thats indeed a WOT (Wall Of Text). I keep it as short as possible :)

1. A merge from master to fork, and generally all merges, can only be done when you have NO local changes in your local repository folder. First you always have to commit every changes to github before do the merge.
2. The `README` problem seems to be related to point 1. If you have no local changes, you should not have any problem merging it.
3. The tools to update the README just take the line were the translation badges are in and replace that numbers. All other stuff is untouched.
4. `resource.dat` is not packed into the generated `.zip` files. Also it's intended to be ignored in the repository. There are some copyright concern i have. There is a plan from my side to create an installer for the language mods, that automatically modify the required files on a users PC. But because of lack of time, i've not done anything yet.
5. The editor "upload" problem. It seems, that multiple uploads in one session is a bit buggy. Maybe i can do a fix here.

Generally, due the lack of interest for this mods, i not prioritize the work in here. The game seems to be it was a bit overhyped in the beginning. Also from my side. I actually don't play it anymore. When checking some steam stats, it already lost 50% of active players within march.

**Comment by mengpo1** [comment]
Thanks both of you, everything's working fine now. I'll continue the job from now :)

**Comment by pilax** [comment]
Thanks a lot for your answer.

1. I was not aware of the problem and how to proceed.
I would be more attentive on that point next time.
2. It makes sense :)
3. Ok, no problem. I think it was a bug that I had after my hack to correct my problem Merge.
4. Ok I understand for the resources.dat.
No worries take your time to make installer, anyway, as long as we have not finished translating, there is no point in setting it up;)
5. Do not worry about this point either, we have found an alternative to not be confronted with the error message, do not waste your time fixing this part :)

Indeed the hype on the game seems gone, even on my side I have a little less motivation for translation, but I hang on all the same :)
On the other hand, I always start games when I have time!

I also understand that you want to invest your time on something else, but know that the team FR and IT are active and we continue to do the translation, thanks again for the tools made available!

Do not take your head with the fix, it seems to work all the same, and we should no longer be confronted with the previous problems, knowing what are the things to do :)

Thanks again for your answers and your time :)

**Comment by brainfoolong** [comment]
Thanks for being such a great mod community member/members 👍

**Comment by pilax** [comment]
no problem, with pleasure ^^
Thank you for putting this project in place 👍 !

**Comment by pilax** [comment]
Since the update of ITB, I have an error message when I use the command "node update-translation-template.js":
```
D:\Tools\GitHub\ForkIntoTheBreachTranslations\dev>node update-translation-template.js
D:\Tools\GitHub\ForkIntoTheBreachTranslations\node_modules\luaparse\luaparse.js:471
    throw error;
    ^

SyntaxError: [6:1] '}' expected near 'SpawnsPerTurn'
    at raise (D:\Tools\GitHub\ForkIntoTheBreachTranslations\node_modules\luaparse\luaparse.js:460:15)
    at expect (D:\Tools\GitHub\ForkIntoTheBreachTranslations\node_modules\luaparse\luaparse.js:1049:10)
    at parseTableConstructor (D:\Tools\GitHub\ForkIntoTheBreachTranslations\node_modules\luaparse\luaparse.js:1761:5)
    at parseCallExpression (D:\Tools\GitHub\ForkIntoTheBreachTranslations\node_modules\luaparse\luaparse.js:1981:23)
    at parsePrefixExpression (D:\Tools\GitHub\ForkIntoTheBreachTranslations\node_modules\luaparse\luaparse.js:1938:20)
    at parseSubExpression (D:\Tools\GitHub\ForkIntoTheBreachTranslations\node_modules\luaparse\luaparse.js:1860:22)
    at parseExpression (D:\Tools\GitHub\ForkIntoTheBreachTranslations\node_modules\luaparse\luaparse.js:1781:22)
    at parseExpectedExpression (D:\Tools\GitHub\ForkIntoTheBreachTranslations\node_modules\luaparse\luaparse.js:1788:22)
    at parseAssignmentOrCallStatement (D:\Tools\GitHub\ForkIntoTheBreachTranslations\node_modules\luaparse\luaparse.js:1610:15)
    at parseStatement (D:\Tools\GitHub\ForkIntoTheBreachTranslations\node_modules\luaparse\luaparse.js:1316:12)
```

I executed "npm install" as well as "npm i -g npm" (because there was an update), but the error message persists.

So I'm afraid I do not have the latest version of template.json, although I did the one on your Master last night.

Can you enlighten me on this?

**Comment by brainfoolong** [comment]
Don't mind about that script, i have done this with my latest master update 3 days ago https://github.com/brainfoolong/IntoTheBreachTranslations/commit/7af3c1d9533cc8f63c371cbacb0c2dc3fbea5b5a It does only modify the `template.json` file that holds the template strings. In my master is everything up 2 date.

**Comment by pilax** [comment]
Ok, no problem.
Thanks you

**Comment by pilax** [comment]
Hi Brain,
It's still me, the bug finder ;)

Now that we have finished the translation, we are testing it and we have seen some problems.
I will not list them all here, but describe at least two that will allow you to hopefully find the solution and correct some of the other problems I suppose.

I start with the simplest:
When we start a new game, there are 2 problems:
- Instead of the "Back" button appears "No String Found"
It is however translated in the tool "Translation Editor" and does not correspond to any image.
- The "Start" button remains in English.
No translation line appears in the "Translation Editor" tool and does not correspond to any image.
- The text "Difficulty" remains in English.
It is however translated in the tool "Translation Editor" and does not correspond to any image.

In the same spirit, when you are in game and you display the pause menu with "Esc."
Squad Achivevements, Island Progress, Timeline Playtime and Difficulty remains in English and line does not appears (except "difficulty" which is translated, but which must not be linked at once) in the "Translation Editor" tool and does not correspond to any image.


The Other problem is more complex I think, it concerns the special description of the pilots who remains in English in start menu and in game.
More precisely their first skill, because the second is the third is correctly translated in game.

- For exemple with the first Pilot (the case is the same for all the others) : 
**Ralph Karlsson
"Gain +2 bonus XP per kill"**
No translation line appears in the "Translation Editor" tool and does not correspond to any image.
But in the "pilots.csv" file I found these lines that are not translated
```
Ralph Karlsson
Id = "Pilot_Original",
Skill = +1 XP per kill
```
And strange thing, this description is not the same as displayed in the game.
I explain myself with two other pilots, between what is displayed in the game and what is in the pilot.csv file.
- Abe Isamu 
_IG Special_ : Mech gains Armored
_pilots.csv_ : Id = "Pilot_Assassin",
Skill = Deploys anywhere on the map, dealing damage to adj.

- Chen Rong
_IG Special_ : After attacking, gain 1 free tile movement.
_pilots.csv_ : Id = "Pilot_Leader",
Skill = 1 tile free move after attacking

We can also notice the inconsistency between the display in game and the one in the file.

Here are the two main problems we encounter.
I think that those who remain here and there are more or less connected with those mentioned above.

I don't know if it can be fixed, or if it is hardcoded, but I hope you can find a solution :)

Thanks to you in advance, and as usual, I remain available if you need additional information or tests.

**Comment by brainfoolong** [comment]
The pilots thingy is really weird, i noticed that already when i've made the extraction tools for that. This file is all, but not readable.

About all "untranslated" things in-game, you can probably find the missing part in the game files by simply search in all game files for given texts. If you have found it, i can add it to the tools that replace the translations.

For example for `Squad Achivevements`: Search your game whole files for this text, if found, modify it and watch if it changes in-game. If yes, please give me the information where and what you have found. It's that silly, i know. But that's the only way of finding each remaining problem...

I also found some "untranslatable" texts myself during testing, but i don't remember anymore what those was.

**Comment by pilax** [comment]
Thank you for your answer :)

Ok, it's going to be a long investigation, if I find something I'll share with you in order to integrate it into the tool.

Case to follow.. :)

**Comment by pilax** [comment]
Just for info after a little research, it seems that some things are directly in breach.exe and not editable with ResHack.
By searching Timeline Playtime "for example, we find it line 17328 of breach.exe

So we have to decompile, modify and recompile, if we can do it and if we are allowed to do it by the dev of the game.

So I think that the top we are beaten and that we will not be able to do much: /

Unless you have a miracle solution: D

**Comment by brainfoolong** [comment]
As you've said it, i think we are on a point where it requires exponential more work for exponential less reward. I think, that view missing translations are not worth the time that you/we investigate.

I will do my thing to include the resource.dat in our translation packages and i think that should be it, unless the game devs put out some new game stuff, which i barely expect.

**Comment by brainfoolong** [comment]
Ok `resource.dat` is finally in the `fr.zip` package.

**Comment by pilax** [comment]
Oh nice, thanks you :)
